### ISSUE TITLE
Compile fails in JSONParserUtils.java

### ISSUE THREAD

**Issue by karianna** [blekione/WotApp#1]
[ERROR] /Users/karianna/Documents/workspace/LJC/WotApp/WotRestApp/src/main/java/org/krugdev/auxiliary/JSONParserUtils.java:[39,55] incompatible types: inference variable T has incompatible bounds
    equality constraints: capture#1 of ?
    upper bounds: java.lang.Object[],java.lang.Object

**Comment by blekione** [comment]
resolved

**Comment by karianna** [comment]
Still fails for me, even after pulling from your master branch...

**Comment by blekione** [comment]
Had same issues last night as I made some major changes to this element and I also upgraded the dependencies of jboss RESTeasy components to the newer versions. 

This error appears when return value from Gson.fromJson() is not cast to expected class.

I made the dependencies upgrades as not all the functionalities which I want to use were supported in the version I was using.

Now should be OK as I ran all the tests through `mvn test` and `mvn clean install `(which gave me that error) and all looks good so far. 

I have replaced JSONParserUtils class by redesigned JSONToObjectBuilder class. I feel that now I have better decoupling of my service from GSON and separation of concerns. Now all the logic which uses GSON is in one class.

**Comment by karianna** [comment]
Yep all good now.

**Comment by blekione** [comment]
Had same issues last night as I made some major changes to this element and
I also upgraded the dependencies of jboss RESTeasy components to the newer
versions. Now should be OK as I ran all the tests through mvn test and mvn
clean install (which gives me that error) and all looks good so far. I
replace JSONParserUtils class with redesigned JSONToObjectBuilder class. I
feel now I have better decoupling of my classes from GSON and separation of
concerns. Now all the logic which uses GSON is in one class.
I made the dependencies upgrades as not all the functionalities which I
want to use were supported in the version I was using.

Regards
Marcin

**Comment by blekione** [comment]
Oh and error is caused when return value from Gson.fromJson() is not casted
to expected class.

On 24 Oct 2016 08:07, "Marcin Kruglik" <blekione@gmail.com> wrote:

Had same issues last night as I made some major changes to this element and
I also upgraded the dependencies of jboss RESTeasy components to the newer
versions. Now should be OK as I ran all the tests through mvn test and mvn
clean install (which gives me that error) and all looks good so far. I
replace JSONParserUtils class with redesigned JSONToObjectBuilder class. I
feel now I have better decoupling of my classes from GSON and separation of
concerns. Now all the logic which uses GSON is in one class.
I made the dependencies upgrades as not all the functionalities which I
want to use were supported in the version I was using.

Regards
Marcin
